environments:
  default:
    values:
      - helm/values.yaml
  dev:
    values:
      - helm/values.yaml
      - releaseName: dev-torus-docs
      - ingressHost: dev.docs.torus.network
  prod:
    values:
      - helm/values.yaml
      - releaseName: torus-docs
      - ingressHost: docs.torus.network
---
helmDefaults:
  wait: true
  createNamespace: false

repositories:
  - name: renlabs
    url: https://charts.renlabs.dev/

releases:
  - name: "{{ .Values.releaseName }}"
    namespace: torus-docs
    chart: renlabs/application
    values:
      - helm/values.yaml.gotmpl
      - ingress:
          hosts:
            - host: "{{ .Values.ingressHost }}"
              paths:
                - path: /
                  pathType: Prefix