name: Build and deploy to Fly.io

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          package_json_file: ./package.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  
          FLY_APP: ${{ vars.APP_NAME }}
